### ISSUE TITLE
Examples don't appear Library-focused

### ISSUE THREAD

**Issue by emcaulay** [LibraryCarpentry/lc-overview#24]
In the section with the heading, "Libraries are guided by the needs of their communities…" it feels like the bullet points are copied from a different Carpentries (Data or Software). 

If they are the intended bullet points, I think we should connect the dots between the assertions about what researchers need and the role of library-related staff. Happy to help with this, but I feel like I should connect with someone with more experience with this lesson. 

Thanks!

**Comment by libcce** [comment]
@emcaulay the supporting material for the bullets (researcher needs) are below the list. For instance, industry is looking for data savvy candidates is linked to Investing in America's data science talent... The content comes form slides I used often to introduce LC and tie it to the overall Carpentries. If you think there is other supporting material/points to add, that will be great! For instance, my LC role was a US funded position and so that section leans more towards the US. It should be more inclusive of what is happening in other countries.

**Comment by emcaulay** [comment]
Okay, thanks for providing the context, @libcce! I will read again and either make some suggestions or close this issue. I appreciate the discussion!

**Comment by emcaulay** [comment]
I'm going to close this issue because I am just getting oriented to the Library Carpentry lessons, and I don't think I'm experienced enough to make effective edits to this lesson. I am always open to talking about it if anyone wants to discuss further. 

Thanks, @libcce !
