### ISSUE TITLE
Extended time estimates for online workshops

### ISSUE THREAD

**Issue by karenword** [LibraryCarpentry/lc-overview#31]
This issue was submitted via email for Instructor checkout:

"I believe online experiences with direct training and experiential learning (a feature of the Carpentries that is certainly a selling point) require a significant increase in time. Especially for for those modules and portions thereof that are directly related to actual practice of the given code function or syntax, or data tool. In some ways, I feel almost doubling the time expected may be warranted.

The relative size of a shared screen, the detailed user interface elements, and likely an even greater lack of baseline familiarity with data and data tools should be allocated a substantial increase in time for Library Carpentry lessons. In particular, those specific sections involving OpenRefine and R."

**Comment by morskyjezek** [comment]
Thank you for this suggestion! We've certainly learned a lot about offering workshops online and via videoconferencing over the past few years! Since this lesson doesn't include use of OpenRefine, R, or Python, I'm going to close it on this lesson, but I gather it is or has been received for related lessons as well. This issue is one that affects lessons across all of the carpentries areas. 

Thank you!
